In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]],dtype= np.float32)
print(a.ndim)
print(a.shape)
print(a.dtype)

2
(2, 3)
float32


In [4]:
np.ones((3,5), dtype = np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [5]:
np.zeros((6,2), dtype = np.float32)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [6]:
np.arange(1334,1338)

array([1334, 1335, 1336, 1337])

In [12]:
a = np.zeros((2,3))
b = np.ones((4,3))
np.concatenate([a,b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
a = np.zeros((4,3))
b = np.ones((4,6))
np.concatenate([a,b], axis = 1)

array([[0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [16]:
a = np.ones((2,3))
b = np.zeros_like(a)
print(a)
print(b)
print(b.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [18]:
np.random.random((10,10))

array([[0.95308162, 0.08256256, 0.93123266, 0.07193744, 0.1999186 ,
        0.98057127, 0.13101949, 0.8700839 , 0.23381576, 0.06634026],
       [0.40841685, 0.21818306, 0.49557848, 0.76131499, 0.31612897,
        0.28766078, 0.44185335, 0.18317797, 0.49913837, 0.50037803],
       [0.46258874, 0.10666585, 0.96638827, 0.73985476, 0.09452946,
        0.69956083, 0.82925879, 0.0461001 , 0.30617522, 0.80877007],
       [0.79954796, 0.77373133, 0.89459344, 0.17221228, 0.13522116,
        0.22843539, 0.58093844, 0.95149585, 0.1078838 , 0.66448304],
       [0.47084065, 0.23485988, 0.96537161, 0.72184993, 0.79065954,
        0.73785295, 0.66037459, 0.71082872, 0.96802422, 0.33608997],
       [0.45045012, 0.57743893, 0.54316693, 0.3994746 , 0.11195602,
        0.48791324, 0.00197777, 0.0139194 , 0.62105359, 0.04299132],
       [0.30092833, 0.79563427, 0.05946191, 0.53111557, 0.25039924,
        0.27225563, 0.07084796, 0.54872029, 0.91016766, 0.03446669],
       [0.70519678, 0.57366856, 0.4927932

In [5]:
# Shaping

a= np.array([1,2,3,4,5,6])
a = a.reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
a = a.reshape(2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a = np.arange(10).reshape(5,2)
print(a)
print("--------------------------------")
a = a.T
print(a)
print("--------------------------------")
a = a.transpose((1,0))
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
--------------------------------
[[0 2 4 6 8]
 [1 3 5 7 9]]
--------------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
a = np.array([1,2,3])
b = np.array([5,5,6])
a*b

array([ 5, 10, 18])

In [31]:
a = np.array([5,6,6,7])
a>0

array([ True,  True,  True,  True])

In [35]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x = x.reshape((5,2))
print(x)
print(x[0,0])
print(x[0,-1])
print(x[0,:])
print(x[:,0])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
1
2
[1 2]
[1 3 5 7 9]


In [40]:
print(x.sum())
print(x.sum(axis = 0))
print(x.sum(axis = 1))

55
[25 30]
[ 3  7 11 15 19]


In [41]:
print(x.sum(axis = 1,keepdims = True))

[[ 3]
 [ 7]
 [11]
 [15]
 [19]]
